version: "3.9"

services:

  app:
    restart: "unless-stopped"
    build:
      context: .
    volumes:
      #- .:/app
      - ./models:/app/models
    environment:
      APP_WORKERS: 10
    ports:
      - "127.0.0.1:8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
